In [51]:
#import libraries some of them are listed in  requirements.txt
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
df = pd.read_csv(r'E:\TPMS\data\raw\configuration_data.csv')
df.head()

,vehicle_id,vehicle_type,axle_configuration,axle_count,wheel_count,gvwr_kg,curb_weight,tire_brand,model,size,ply_rating,max_pressure_psi,idel_temp,max_load_single_kg,section_width_mm,overall_diameter_mm,initial_tread,tyre_life
0,MH14JK7645,TRUCK,4x2,2,6,16200,7500,MRF,SUPERLUG,11.00-22,16,118.5,60,3525 kg,3090mm,1160 mm,21.5,120000 km
1,RJ21LM7621,Semi-Trailer,6x4,3,10,25000,8500,Michelin,X Line Energy,295/80R22.5,16,120.0,65,3550 kg,298 mm,1044 mm,18.5,165000 km
2,MH47MD4509,Box Van,4x2,2,4,7500,3200,Bridgestone,Duravis R660,225/75R16C,10,65.0,50,1450 kg,225 mm,744 mm,9.0,65000 km
3,MH12XD7689,Pickup,6x2,2,8,3500,2100,Goodyear,Wrangler AT,265/70R17,8,50.0,55,1120 kg,265 mm,804 mm,12.2,55000 km

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   vehicle_id           4 non-null      object
 1   vehicle_type         4 non-null      object
 2   axle_configuration   4 non-null      object
 3   axle_count           4 non-null      int64
 4   wheel_count          4 non-null      int64
 5   gvwr_kg              4 non-null      int64
 6   curb_weight          4 non-null      int64
 7   tire_brand           4 non-null      object
 8   model                4 non-null      object
 9   size                 4 non-null      object
 10  ply_rating           4 non-null      int64
 11  max_pressure_psi     4 non-null      float64
 12  idel_temp            4 non-null      int64
 13  max_load_single_kg   4 non-null      object
 14  section_width_mm     4 non-null      object
 15  overall_diameter_mm  4 non-null      object
 16  initial_tread        4 non-null      float64
 17  tyre_life            4 non-null      object
dtypes: float64(2), int64(6), object(10)
memory usage: 708.0+ bytes

In [53]:
print(df.isnull().sum())
print(df.duplicated().sum())
df.shape

vehicle_id             0
vehicle_type           0
axle_configuration     0
axle_count             0
wheel_count            0
gvwr_kg                0
curb_weight            0
tire_brand             0
model                  0
size                   0
ply_rating             0
max_pressure_psi       0
idel_temp              0
max_load_single_kg     0
section_width_mm       0
overall_diameter_mm    0
initial_tread          0
tyre_life              0
dtype: int64
0

(4, 18)

In [54]:
Object_columns = df[['max_load_single_kg','section_width_mm','overall_diameter_mm','tyre_life']]
Object_columns.head()

  max_load_single_kg section_width_mm overall_diameter_mm  tyre_life
0           3525 kg            3090mm             1160 mm  120000 km
1            3550 kg           298 mm             1044 mm  165000 km
2            1450 kg           225 mm              744 mm   65000 km
3            1120 kg           265 mm              804 mm   55000 km

In [55]:
#striping units form the object columns and converting them to numeric values
Object_columns = Object_columns.apply(lambda x: x.str.replace(r'[^\d\.]', '', regex=True))
Object_columns = Object_columns.apply(pd.to_numeric)
print(Object_columns.dtypes)
print(Object_columns.head())

max_load_single_kg     int64
section_width_mm       int64
overall_diameter_mm    int64
tyre_life              int64
dtype: object
   max_load_single_kg  section_width_mm  overall_diameter_mm  tyre_life
0                3525              3090                 1160     120000
1                3550               298                 1044     165000
2                1450               225                  744      65000
3                1120               265                  804      55000

In [56]:
#split the axle_configuration column into two separate columns for front and rear axle configurations
df[['total_wheels','driven_wheels']] = df['axle_configuration'].str.split('x', expand=True)
#convert the extraceted strings into int 64
df['total_wheels'] = pd.to_numeric(df['total_wheels'], errors='coerce')
df['driven_wheels'] = pd.to_numeric(df['driven_wheels'], errors='coerce')
df.head()

,vehicle_id,vehicle_type,axle_configuration,axle_count,wheel_count,gvwr_kg,curb_weight,tire_brand,model,size,ply_rating,max_pressure_psi,idel_temp,max_load_single_kg,section_width_mm,overall_diameter_mm,initial_tread,tyre_life,total_wheels,driven_wheels
0,MH14JK7645,TRUCK,4x2,2,6,16200,7500,MRF,SUPERLUG,11.00-22,16,118.5,60,3525 kg,3090mm,1160 mm,21.5,120000 km,4,2
1,RJ21LM7621,Semi-Trailer,6x4,3,10,25000,8500,Michelin,X Line Energy,295/80R22.5,16,120.0,65,3550 kg,298 mm,1044 mm,18.5,165000 km,6,4
2,MH47MD4509,Box Van,4x2,2,4,7500,3200,Bridgestone,Duravis R660,225/75R16C,10,65.0,50,1450 kg,225 mm,744 mm,9.0,65000 km,4,2
3,MH12XD7689,Pickup,6x2,2,8,3500,2100,Goodyear,Wrangler AT,265/70R17,8,50.0,55,1120 kg,265 mm,804 mm,12.2,55000 km,6,2

In [57]:
#updating the original datafram with the cleaned numeric columns
df[['max_load_single_kg','section_width_mm','overall_diameter_mm','tyre_life']] = Object_columns
#now separating numeric columns and categorical columns
numeric_columns = df.select_dtypes(include=[np.number])
categorical_columns = df.select_dtypes(exclude=[np.number])
print("Numeric Columns:")
print(numeric_columns.columns)
print("\nCategorical Columns:")
print(categorical_columns.columns)

Numeric Columns:
Index(['axle_count', 'wheel_count', 'gvwr_kg', 'curb_weight', 'ply_rating',
       'max_pressure_psi', 'idel_temp', 'max_load_single_kg',
       'section_width_mm', 'overall_diameter_mm', 'initial_tread', 'tyre_life',
       'total_wheels', 'driven_wheels'],
      dtype='object')

Categorical Columns:
Index(['vehicle_id', 'vehicle_type', 'axle_configuration', 'tire_brand',
       'model', 'size'],
      dtype='object')

In [60]:
# check current column names before calculation
print(df.columns)

# compute derived features using actual column names
# driven ratio is percentage of wheels that are driven
df['driven_ratio'] = df['driven_wheels'] / df['total_wheels']

# ensure gvwr and curb weight are numeric
for col in ['gvwr_kg', 'curb_weight']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# load per wheel (subtract curb weight from GVWR)
df['load_per_wheel'] = (df['gvwr_kg'] - df['curb_weight']) / df['total_wheels']

# drive stress factor
# avoid division by zero by filling driven_ratio zeros with nan
df['drive_stress_factor'] = df['load_per_wheel'] / df['driven_ratio'].replace({0: np.nan})

Index(['vehicle_id', 'vehicle_type', 'axle_configuration', 'axle_count',
       'wheel_count', 'gvwr_kg', 'curb_weight', 'tire_brand', 'model', 'size',
       'ply_rating', 'max_pressure_psi', 'idel_temp', 'max_load_single_kg',
       'section_width_mm', 'overall_diameter_mm', 'initial_tread', 'tyre_life',
       'total_wheels', 'driven_wheels', 'driven_ratio'],
      dtype='object')

In [ ]:
#updating this new datafram and saving it into E:\TPMS\data\processed location
df.to_csv(r'E:\TPMS\data\processed\cleaned_configuration_data.csv', index=False)